/**
 * ⚠️  READ/UPDATE STATUS.md BEFORE & AFTER CHANGES
 * Package: @greenlight/db/types | Status: [Check STATUS.md] | Modified: 2025-10-17
 */

// This file will be auto-generated by: npm run gen:types
// Run this command after applying migrations to Supabase:
// supabase gen types typescript --local > types/database.ts

// For now, we provide a placeholder type definition
// This will be replaced with actual generated types once Supabase is configured

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      org: {
        Row: {
          id: string;
          name: string;
          npi: string | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          npi?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          npi?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      member: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: string;
          status: string;
          has_seen_tour: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          role?: string;
          status?: string;
          has_seen_tour?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          has_seen_tour?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      super_admin: {
        Row: {
          id: string;
          user_id: string;
          granted_by: string | null;
          granted_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          granted_by?: string | null;
          granted_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          granted_by?: string | null;
          granted_at?: string;
          notes?: string | null;
        };
        Relationships: [];
      };
      patient: {
        Row: {
          id: string;
          org_id: string;
          mrn: string | null;
          name: string;
          dob: string | null;
          sex: string | null;
          phone: string | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          mrn?: string | null;
          name: string;
          dob?: string | null;
          sex?: string | null;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          mrn?: string | null;
          name?: string;
          dob?: string | null;
          sex?: string | null;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      payer: {
        Row: {
          id: string;
          name: string;
          portal_url: string | null;
          contact: string | null;
          policy_links: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          portal_url?: string | null;
          contact?: string | null;
          policy_links?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          portal_url?: string | null;
          contact?: string | null;
          policy_links?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      coverage: {
        Row: {
          id: string;
          org_id: string;
          patient_id: string;
          payer_id: string;
          plan_name: string | null;
          group_no: string | null;
          member_id: string | null;
          eligibility_checked_at: string | null;
          raw_json: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          patient_id: string;
          payer_id: string;
          plan_name?: string | null;
          group_no?: string | null;
          member_id?: string | null;
          eligibility_checked_at?: string | null;
          raw_json?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          patient_id?: string;
          payer_id?: string;
          plan_name?: string | null;
          group_no?: string | null;
          member_id?: string | null;
          eligibility_checked_at?: string | null;
          raw_json?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      provider: {
        Row: {
          id: string;
          org_id: string;
          npi: string | null;
          name: string;
          specialty: string | null;
          location: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          npi?: string | null;
          name: string;
          specialty?: string | null;
          location?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          npi?: string | null;
          name?: string;
          specialty?: string | null;
          location?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      order: {
        Row: {
          id: string;
          org_id: string;
          patient_id: string;
          provider_id: string | null;
          modality: string;
          cpt_codes: string[];
          icd10_codes: string[];
          clinic_notes_text: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          patient_id: string;
          provider_id?: string | null;
          modality: string;
          cpt_codes: string[];
          icd10_codes: string[];
          clinic_notes_text?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          patient_id?: string;
          provider_id?: string | null;
          modality?: string;
          cpt_codes?: string[];
          icd10_codes?: string[];
          clinic_notes_text?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pa_request: {
        Row: {
          id: string;
          org_id: string;
          order_id: string;
          payer_id: string | null;
          priority: string;
          status: string;
          created_by: string | null;
          submitted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          order_id: string;
          payer_id?: string | null;
          priority?: string;
          status?: string;
          created_by?: string | null;
          submitted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          order_id?: string;
          payer_id?: string | null;
          priority?: string;
          status?: string;
          created_by?: string | null;
          submitted_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pa_checklist_item: {
        Row: {
          id: string;
          pa_request_id: string;
          name: string;
          rationale: string | null;
          required_bool: boolean;
          status: string;
          evidence_attachment_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pa_request_id: string;
          name: string;
          rationale?: string | null;
          required_bool?: boolean;
          status?: string;
          evidence_attachment_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          pa_request_id?: string;
          name?: string;
          rationale?: string | null;
          required_bool?: boolean;
          status?: string;
          evidence_attachment_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pa_summary: {
        Row: {
          id: string;
          pa_request_id: string;
          medical_necessity_text: string;
          indications_text: string | null;
          risk_benefit_text: string | null;
          generated_by_model: string | null;
          version: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          pa_request_id: string;
          medical_necessity_text: string;
          indications_text?: string | null;
          risk_benefit_text?: string | null;
          generated_by_model?: string | null;
          version?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          pa_request_id?: string;
          medical_necessity_text?: string;
          indications_text?: string | null;
          risk_benefit_text?: string | null;
          generated_by_model?: string | null;
          version?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      attachment: {
        Row: {
          id: string;
          org_id: string;
          storage_path: string;
          type: string;
          ocr_text: string | null;
          sha256: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          storage_path: string;
          type: string;
          ocr_text?: string | null;
          sha256?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          storage_path?: string;
          type?: string;
          ocr_text?: string | null;
          sha256?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      status_event: {
        Row: {
          id: string;
          pa_request_id: string;
          status: string;
          note: string | null;
          actor: string | null;
          at: string;
        };
        Insert: {
          id?: string;
          pa_request_id: string;
          status: string;
          note?: string | null;
          actor?: string | null;
          at?: string;
        };
        Update: {
          id?: string;
          pa_request_id?: string;
          status?: string;
          note?: string | null;
          actor?: string | null;
          at?: string;
        };
        Relationships: [];
      };
      policy_snippet: {
        Row: {
          id: string;
          payer_id: string | null;
          modality: string | null;
          cpt_code: string | null;
          snippet_text: string;
          source_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          payer_id?: string | null;
          modality?: string | null;
          cpt_code?: string | null;
          snippet_text: string;
          source_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          payer_id?: string | null;
          modality?: string | null;
          cpt_code?: string | null;
          snippet_text?: string;
          source_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          org_id: string | null;
          user_id: string | null;
          action: string;
          subject: string | null;
          subject_id: string | null;
          meta_json: Json | null;
          at: string;
        };
        Insert: {
          id?: string;
          org_id?: string | null;
          user_id?: string | null;
          action: string;
          subject?: string | null;
          subject_id?: string | null;
          meta_json?: Json | null;
          at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          user_id?: string | null;
          action?: string;
          subject?: string | null;
          subject_id?: string | null;
          meta_json?: Json | null;
          at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {
      get_user_org_ids: {
        Args: { user_uuid: string };
        Returns: string[];
      };
      is_org_admin: {
        Args: { user_uuid: string; org_uuid: string };
        Returns: boolean;
      };
    };
    Enums: {
      pa_status:
        | "draft"
        | "submitted"
        | "pending_info"
        | "approved"
        | "denied"
        | "appealed";
      evidence_status: "pending" | "attached" | "waived";
      attachment_type:
        | "order"
        | "imaging"
        | "lab"
        | "notes"
        | "payer_form"
        | "appeal"
        | "other";
    };
  };
}
