/**
 * ⚠️  READ/UPDATE STATUS.md BEFORE & AFTER CHANGES
 * Package: @greenlight/pdfkit/templates/cover-letter | Status: [Check STATUS.md] | Modified: 2025-10-17
 */

import {
  createPDF,
  pdfToBuffer,
  addHeader,
  addSection,
  addList,
  addFooter,
  type PDFResult,
} from "../generator";

/**
 * Cover Letter Data
 */
export interface CoverLetterData {
  // Organization info
  orgName: string;
  orgAddress: string;
  orgPhone?: string;
  orgFax?: string;

  // Payer info
  payerName: string;
  payerAddress?: string;

  // Patient info (de-identified)
  patientName: string;
  patientDOB: string;
  patientMemberID: string;

  // Provider info
  providerName: string;
  providerNPI: string;
  providerSpecialty?: string;

  // PA Request info
  paRequestNumber: string;
  submissionDate: string;
  modality: string;
  cptCodes: string[];
  icd10Codes: string[];
  priority: "standard" | "urgent";

  // Attachments list
  attachments: Array<{
    name: string;
    type: string;
  }>;
}

/**
 * Generate PA Cover Letter PDF
 */
export async function generateCoverLetter(
  data: CoverLetterData
): Promise<PDFResult> {
  try {
    const doc = createPDF({
      title: `PA Cover Letter - ${data.paRequestNumber}`,
      subject: `Prior Authorization Request for ${data.patientName}`,
      keywords: `PA, Prior Authorization, ${data.modality}`,
    });

    // Header
    addHeader(
      doc,
      "Prior Authorization Request",
      `PA Request #${data.paRequestNumber}`
    );

    // Date
    doc
      .fontSize(11)
      .text(`Date: ${data.submissionDate}`, { align: "right" })
      .moveDown(1.5);

    // To Section
    addSection(doc, "To:", data.payerName);
    if (data.payerAddress) {
      doc.fontSize(11).text(data.payerAddress).moveDown(1);
    }

    // From Section
    addSection(doc, "From:", data.orgName);
    doc.fontSize(11).text(data.orgAddress);
    if (data.orgPhone) {
      doc.text(`Phone: ${data.orgPhone}`);
    }
    if (data.orgFax) {
      doc.text(`Fax: ${data.orgFax}`);
    }
    doc.moveDown(1);

    // Priority indicator
    if (data.priority === "urgent") {
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .fillColor("#d32f2f")
        .text("*** URGENT REVIEW REQUESTED ***", { align: "center" })
        .fillColor("#000")
        .font("Helvetica")
        .moveDown(1);
    }

    // Patient Information
    addSection(doc, "Patient Information");
    doc.fontSize(11).text(`Name: ${data.patientName}`);
    doc.text(`Date of Birth: ${data.patientDOB}`);
    doc.text(`Member ID: ${data.patientMemberID}`);
    doc.moveDown(1);

    // Ordering Provider Information
    addSection(doc, "Ordering Provider");
    doc.fontSize(11).text(`Name: ${data.providerName}`);
    doc.text(`NPI: ${data.providerNPI}`);
    if (data.providerSpecialty) {
      doc.text(`Specialty: ${data.providerSpecialty}`);
    }
    doc.moveDown(1);

    // Requested Service
    addSection(doc, "Requested Service");
    doc.fontSize(11).text(`Procedure/Modality: ${data.modality}`);
    doc.text(`CPT Code(s): ${data.cptCodes.join(", ")}`);
    doc.text(`Diagnosis Code(s) (ICD-10): ${data.icd10Codes.join(", ")}`);
    doc.moveDown(1);

    // Medical Necessity Statement
    addSection(
      doc,
      "Medical Necessity",
      "This prior authorization request is submitted based on documented medical necessity as detailed in the attached clinical documentation. The requested service is medically appropriate and indicated for the patient's diagnosis and clinical presentation."
    );

    // Attached Documents
    addSection(doc, "Attached Documents");
    const attachmentList = data.attachments.map(
      (att) => `${att.name} (${att.type})`
    );
    addList(doc, attachmentList);

    // Certification Statement
    addSection(
      doc,
      "Certification",
      "I certify that the information provided in this prior authorization request is true and accurate to the best of my knowledge. The requested service is medically necessary for the diagnosis and treatment of the patient's condition."
    );

    doc.moveDown(2);

    // Signature line
    doc
      .fontSize(11)
      .text("_________________________________________")
      .moveDown(0.3);
    doc.text(`${data.providerName}, ${data.providerSpecialty || "MD"}`);
    doc.text(`NPI: ${data.providerNPI}`);
    doc.text(`Date: ${data.submissionDate}`);

    // Footer
    addFooter(doc, `Generated by Greenlight PA | ${data.orgName}`, true);

    // Convert to buffer
    const buffer = await pdfToBuffer(doc);

    return {
      success: true,
      buffer,
    };
  } catch (error) {
    console.error("Cover letter generation error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "PDF generation failed",
    };
  }
}
